export const template = `# AGENTS.md — {{project.name}}

> Generated by agentctx on {{meta.generatedAt}}.

## Project Overview

**Stack:** Express.js{{#if stack.primary.version}} {{stack.primary.version}}{{/if}}
**Language:** {{stack.language}}
**Package Manager:** {{stack.packageManager}}

## Architecture

Express.js REST API. Typical layout:
- \`src/routes/\` or \`src/api/\` — route handlers
- \`src/middleware/\` — shared middleware (auth, validation, logging)
- \`src/controllers/\` — business logic separated from routing
- \`src/models/\` or \`src/db/\` — data access layer

## Directory Structure

| Path | Purpose |
|------|---------|
{{#if structure.sourceDir}}| \`{{structure.sourceDir}}/\` | Source code |
{{/if}}{{#if structure.testDir}}| \`{{structure.testDir}}/\` | Tests |
{{/if}}| \`src/routes/\` | Route definitions |
| \`src/middleware/\` | Express middleware |

## Development Commands

\`\`\`bash
{{stack.packageManager}} install
{{stack.packageManager}} run dev       # dev server with watch (nodemon/tsx)
{{stack.packageManager}} run build     # compile TypeScript
{{stack.packageManager}} run start     # start compiled server
{{#if conventions.testRunner}}{{stack.packageManager}} run test    # {{conventions.testRunner}}{{/if}}
{{#if conventions.linter}}{{stack.packageManager}} run lint    # {{conventions.linter}}{{/if}}
\`\`\`

## Conventions

{{#if conventions.linter}}- **Linter:** {{conventions.linter}}{{/if}}
{{#if conventions.formatter}}- **Formatter:** {{conventions.formatter}}{{/if}}
{{#if conventions.testRunner}}- **Tests:** {{conventions.testRunner}}{{/if}}
- Return consistent JSON shapes: \`{ data, error, meta }\`
- Use HTTP status codes correctly — never 200 for errors

## Agent Workflow

1. Check existing route patterns in \`src/routes/\` before adding new endpoints
2. Validate inputs at the route level — never trust \`req.body\` directly
3. Centralize error handling via a single error-handler middleware
4. Keep controllers thin — delegate business logic to services
5. Environment variables: only via \`process.env\` — never hardcode
`;
