export const template = `# AGENTS.md — {{project.name}}

> Generated by agentctx on {{meta.generatedAt}}. Edit freely — run \`agentctx update\` to refresh auto-detected sections.

## Project Overview

**Stack:** {{stack.primary.name}}
**Language:** {{stack.language}}
**Package Manager:** {{stack.packageManager}}
{{#if stack.isMonorepo}}**Type:** Monorepo{{/if}}

## Development Setup

<!-- Add setup instructions here -->

## Project Structure

{{#if structure.sourceDir}}- \`{{structure.sourceDir}}/\` — source code{{/if}}
{{#if structure.testDir}}- \`{{structure.testDir}}/\` — tests{{/if}}
{{#if structure.hasDocker}}- Docker support detected{{/if}}

## Conventions

{{#if conventions.linter}}- **Linter:** {{conventions.linter}}{{/if}}
{{#if conventions.formatter}}- **Formatter:** {{conventions.formatter}}{{/if}}
{{#if conventions.testRunner}}- **Tests:** {{conventions.testRunner}}{{/if}}

## Agent Workflow

1. Read existing code patterns before writing new code
2. Follow the conventions listed above
3. Add tests for significant changes
4. Never hardcode secrets — use environment variables
`;
