export const template = `# AGENTS.md — {{project.name}}

> Generated by agentctx on {{meta.generatedAt}}.

## Project Overview

**Stack:** {{stack.primary.name}}
**Language:** Python
**Package Manager:** {{stack.packageManager}}

## Architecture

Django MVT (Model-View-Template) project.

## Development Commands

\`\`\`bash
pip install -r requirements.txt  # Install dependencies
python manage.py runserver        # Start dev server (http://localhost:8000)
python manage.py migrate          # Apply migrations
python manage.py makemigrations   # Create new migrations
python manage.py test             # Run tests
python manage.py createsuperuser  # Create admin user
\`\`\`

## Directory Structure

\`\`\`
manage.py
<app_name>/
  models.py      # Database models
  views.py       # Request handlers
  urls.py        # URL routing
  admin.py       # Admin interface
  tests.py       # Tests
  migrations/    # Database migrations
\`\`\`

## Conventions

- Models: use class-based models with Meta class
- Views: prefer class-based views (CBVs) for complex logic, function-based for simple endpoints
- URLs: use \`path()\` not \`url()\`, use named patterns
- Migrations: always create migrations for model changes, review before committing
- Secrets: use environment variables via \`os.environ\` or \`django-environ\` — never hardcode in settings.py

## Agent Workflow

1. Check existing models before creating new ones
2. Always create migrations after model changes
3. Follow Django ORM patterns — avoid raw SQL unless profiling proves necessary
4. Use Django's built-in authentication system
5. Run \`python manage.py test\` before marking work complete
`;
