import fs from 'node:fs/promises';
import path from 'node:path';
import type { Reporter } from '../ui/reporter.js';
import { StackDetector } from '../core/detector/index.js';
import { ProjectAnalyzer } from '../core/analyzer/index.js';
import { deepScan } from '../core/analyze/deep-scanner.js';
import { scanFeatures } from '../core/scanner/feature-scanner.js';
import { SecretScanner } from '../security/secret-scanner.js';
import { truncate } from '../utils/markdown.js';

export interface AnalyzeOptions {
  readonly targetDir: string;
  readonly dryRun: boolean;
  readonly noRoutes: boolean;
}

const OUTPUT_FILE = 'project-brief.md';
const ROUTE_LIMIT = 30;

export class AnalyzeCommand {
  private readonly secretScanner = new SecretScanner();

  constructor(private readonly reporter: Reporter) {}

  async execute(options: AnalyzeOptions): Promise<void> {
    const { targetDir, dryRun } = options;
    const projectName = path.basename(path.resolve(targetDir));

    this.reporter.section(`Analyzing project: ${projectName}`);

    // Run all scans in parallel
    const [detection, scan] = await Promise.all([
      new StackDetector(targetDir).detect(),
      deepScan(targetDir),
    ]);

    const [analysis, routes] = await Promise.all([
      new ProjectAnalyzer(targetDir).analyze(detection, projectName),
      options.noRoutes ? Promise.resolve([]) : scanFeatures(targetDir),
    ]);

    this.reporter.success(`  Stack: ${detection.primaryStack.name}`);
    this.reporter.success(`  Dirs: ${scan.dirStats.length}, source files: ${scan.totalSourceFiles}, lines: ${scan.totalLines.toLocaleString()}`);
    this.reporter.success(`  Integrations: ${scan.integrations.length}`);
    if (routes.length > 0) this.reporter.success(`  Routes/features: ${routes.length}`);

    const sections: string[] = [];
    const today = new Date().toISOString().split('T')[0]!;

    // ── Header ────────────────────────────────────────────────────────────────
    sections.push(
      `# project-brief.md — ${projectName}\n` +
      `> Generated by agentctx analyze on ${today}.\n` +
      `> Give this file to your AI agent instead of letting it explore the codebase from scratch.\n` +
      `> Regenerate: \`agentctx analyze\``,
    );

    // ── Overview ──────────────────────────────────────────────────────────────
    const overviewLines: string[] = [
      `**Stack:** ${detection.primaryStack.name}`,
      `**Language:** ${analysis.detection.language !== 'unknown' ? analysis.detection.language : detection.primaryStack.name}`,
    ];
    if (analysis.detection.packageManager !== 'unknown') {
      overviewLines.push(`**Package manager:** ${analysis.detection.packageManager}`);
    }
    overviewLines.push(`**Source files:** ${scan.totalSourceFiles} (${scan.totalLines.toLocaleString()} lines)`);
    if (analysis.git.hasGit) {
      overviewLines.push(`**Commits:** ${analysis.git.totalCommits}`);
      if (analysis.git.defaultBranch) overviewLines.push(`**Branch:** ${analysis.git.defaultBranch}`);
    }

    const tools: string[] = analysis.conventions.map((c) => c.tool);
    if (tools.length > 0) overviewLines.push(`**Tools:** ${tools.join(', ')}`);

    sections.push(`## Overview\n\n${overviewLines.join('\n')}`);

    // ── Directory map ─────────────────────────────────────────────────────────
    if (scan.dirStats.length > 0) {
      const rows = scan.dirStats.slice(0, 15).map((d) => {
        const desc = d.description ?? '—';
        return `| \`${d.path}/\` | ${d.sourceCount} | ${desc} |`;
      });
      sections.push(
        `## Directory map\n\n` +
        `| Directory | Source files | Role |\n` +
        `|-----------|-------------|------|\n` +
        rows.join('\n'),
      );
    }

    // ── Key files ─────────────────────────────────────────────────────────────
    if (scan.keyFiles.length > 0) {
      const items = scan.keyFiles.map((f) => `- \`${f.path}\` — ${f.role}`).join('\n');
      sections.push(`## Key files\n\n${items}`);
    }

    // ── Integrations ──────────────────────────────────────────────────────────
    if (scan.integrations.length > 0) {
      const names = scan.integrations.map((i) => i.name).join(', ');
      sections.push(`## Integrations\n\n${names}`);
    }

    // ── Routes / API surface ──────────────────────────────────────────────────
    if (routes.length > 0) {
      const shown = routes.slice(0, ROUTE_LIMIT);
      const rows = shown.map((r) => {
        const files = r.feature.files.slice(0, 2).join(', ') +
          (r.feature.files.length > 2 ? ` +${r.feature.files.length - 2}` : '');
        const firstStep = r.feature.current.flow[0] ?? '—';
        return `| \`${r.feature.id}\` | ${files} | ${truncate(firstStep, 60)} |`;
      });
      const extra = routes.length > ROUTE_LIMIT ? `\n\n_...${routes.length - ROUTE_LIMIT} more routes not shown_` : '';
      sections.push(
        `## Routes / pages (${routes.length})\n\n` +
        `| ID | Files | Description |\n` +
        `|----|-------|-------------|\n` +
        rows.join('\n') + extra,
      );
    }

    // ── Scripts ───────────────────────────────────────────────────────────────
    const scriptEntries = Object.entries(scan.packageScripts);
    if (scriptEntries.length > 0) {
      const items = scriptEntries
        .filter(([k]) => ['dev', 'start', 'build', 'test', 'lint', 'typecheck', 'check'].includes(k))
        .map(([k, v]) => `- \`${k}\`: \`${truncate(v, 80)}\``)
        .join('\n');
      if (items) sections.push(`## Scripts\n\n${items}`);
    }

    // ── Environment variables ─────────────────────────────────────────────────
    if (analysis.envVars.length > 0) {
      const items = analysis.envVars.map((v) => `- \`${v}\``).join('\n');
      sections.push(`## Required env vars\n\n${items}`);
    }

    // ── Agent navigation hints ────────────────────────────────────────────────
    const hints: string[] = [
      `- Read \`project-brief.md\` (this file) at session start — do NOT explore blindly`,
      `- Start with key files listed above to understand entry points`,
    ];
    if (scan.schemaFiles.length > 0) {
      hints.push(`- Database schema: ${scan.schemaFiles.map((f) => `\`${f}\``).join(', ')}`);
    }
    if (scan.integrations.some((i) => i.name.includes('Auth'))) {
      hints.push('- Auth layer detected — check middleware/auth files before touching protected routes');
    }
    if (scan.integrations.some((i) => i.name.includes('Prisma') || i.name.includes('Drizzle'))) {
      hints.push('- ORM detected — run `prisma generate` or check `drizzle.config.ts` before DB operations');
    }
    sections.push(`## Agent navigation hints\n\n${hints.join('\n')}`);

    // ── Assemble ──────────────────────────────────────────────────────────────
    const bundle = sections.join('\n\n') + '\n';

    const secretScan = this.secretScanner.scan(bundle, OUTPUT_FILE);
    if (secretScan.hasSecrets) {
      this.reporter.warn('Secret pattern detected in generated brief — aborting write.');
      for (const f of secretScan.findings) {
        this.reporter.warn(`  Line ${f.line}: ${f.pattern} [${f.severity}]`);
      }
      return;
    }

    const outputPath = path.join(targetDir, OUTPUT_FILE);
    const approxTokens = Math.round(bundle.length / 4);

    if (dryRun) {
      this.reporter.blank();
      this.reporter.dryRun(`Would write ${OUTPUT_FILE} (${approxTokens} tokens estimated):`);
      this.reporter.blank();
      process.stdout.write(bundle + '\n');
      return;
    }

    await fs.writeFile(outputPath, bundle, 'utf-8');
    this.reporter.blank();
    this.reporter.success(`${OUTPUT_FILE} written (~${approxTokens} tokens).`);
    this.reporter.info('Tell your AI agent: "Read project-brief.md before exploring the codebase."');
    this.reporter.info('Add project-brief.md to .gitignore if you prefer not to commit it.');
  }
}
