import fs from 'node:fs/promises';
import path from 'node:path';
import type { Reporter } from '../ui/reporter.js';
import { FeatureRegistryManager } from '../core/features/registry.js';
import { SecretScanner } from '../security/secret-scanner.js';
import {
  extractSection,
  extractFirstBashBlock,
  extractBulletList,
  truncate,
} from '../utils/markdown.js';

export interface ContextOptions {
  readonly targetDir: string;
  readonly dryRun: boolean;
  readonly compact: boolean;
  readonly noFeatures: boolean;
  readonly noDeploy: boolean;
  readonly noArchitecture: boolean;
  readonly noRules: boolean;
}

const OUTPUT_FILE = 'context-bundle.md';
const ARCH_MAX_CHARS = 800;

// ─── Deploy parser ────────────────────────────────────────────────────────────

interface DeployEnv {
  name: string;
  envVars: string[];
  notes?: string;
}

function parseDeployMd(content: string): DeployEnv[] {
  const envs: DeployEnv[] = [];
  const envPattern = /^### (.+)$/gm;
  let match: RegExpExecArray | null;

  while ((match = envPattern.exec(content)) !== null) {
    const name = match[1]!.trim();
    const start = match.index + match[0].length;
    const nextMatch = /^### /m.exec(content.slice(start));
    const block = nextMatch
      ? content.slice(start, start + nextMatch.index)
      : content.slice(start);

    const varMatches = [...block.matchAll(/- `([A-Z_][A-Z0-9_]*)` —/g)];
    const envVars = varMatches.map((m) => m[1]!);

    const notesMatch = block.match(/\*\*Notes:\*\* (.+)/);
    const notes = notesMatch ? notesMatch[1]!.trim() : undefined;

    envs.push({ name, envVars, notes });
  }

  return envs;
}

// ─── Command ──────────────────────────────────────────────────────────────────

export class ContextCommand {
  private readonly scanner = new SecretScanner();

  constructor(private readonly reporter: Reporter) {}

  async execute(options: ContextOptions): Promise<void> {
    const { targetDir, dryRun, compact } = options;

    this.reporter.section('Building context bundle...');

    const sections: string[] = [];
    const today = new Date().toISOString().split('T')[0]!;

    // ── Header ────────────────────────────────────────────────────────────────
    const projectName = path.basename(path.resolve(targetDir));
    sections.push(
      `# context-bundle.md — ${projectName}\n` +
      `> Generated by agentctx on ${today}. ` +
      `Read this at session start to save tokens (~600 tokens vs 8 000+ from individual files).\n` +
      `> Regenerate: \`agentctx context\``,
    );

    // ── Commands & Rules (from CLAUDE.md) ────────────────────────────────────
    const claudeMd = await this.readSafe(targetDir, 'CLAUDE.md');
    if (claudeMd) {
      const cmdSection = extractSection(claudeMd, 'Commands');
      if (cmdSection) {
        const bashBlock = extractFirstBashBlock(cmdSection);
        if (bashBlock) {
          sections.push(`## Commands\n\n\`\`\`bash\n${bashBlock}\n\`\`\``);
          this.reporter.success('  Commands extracted from CLAUDE.md');
        }
      }

      if (!options.noRules) {
        const rulesSection = extractSection(claudeMd, 'Rules');
        if (rulesSection) {
          const rules = extractBulletList(rulesSection);
          if (rules.length > 0) {
            const numbered = rules.map((r, i) => `${i + 1}. ${r}`).join('\n');
            sections.push(`## Rules\n\n${numbered}`);
            this.reporter.success('  Rules extracted from CLAUDE.md');
          }
        }
      }
    } else {
      this.reporter.warn('  CLAUDE.md not found — skipping commands/rules');
    }

    // ── Architecture (from DESIGN.md) ─────────────────────────────────────
    if (!compact && !options.noArchitecture) {
      const designMd = await this.readSafe(targetDir, 'DESIGN.md');
      if (designMd) {
        const arch = extractSection(designMd, 'Architecture');
        if (arch) {
          sections.push(`## Architecture\n\n${truncate(arch, ARCH_MAX_CHARS)}`);
          this.reporter.success('  Architecture extracted from DESIGN.md');
        }
      }
    }

    // ── Features (from FEATURES.md) ──────────────────────────────────────────
    if (!compact && !options.noFeatures) {
      const manager = new FeatureRegistryManager(targetDir);
      const registry = await manager.load();

      if (registry.features.length > 0) {
        const active = registry.features.filter((f) => f.status !== 'deprecated');
        const rows = active.map((f) => {
          const filesShort = f.files.slice(0, 2).join(', ') +
            (f.files.length > 2 ? ` +${f.files.length - 2}` : '');
          const firstStep = f.current.flow[0] ?? '—';
          return `| **${f.id}** | ${filesShort} | ${truncate(firstStep, 60)} |`;
        });

        sections.push(
          `## Features (${active.length} active)\n\n` +
          `| Feature | Key files | First step |\n` +
          `|---------|-----------|------------|\n` +
          rows.join('\n'),
        );
        this.reporter.success(`  ${active.length} features listed from FEATURES.md`);
      }
    }

    // ── Deploy environments (from DEPLOY.md) ─────────────────────────────────
    if (!compact && !options.noDeploy) {
      const deployMd = await this.readSafe(targetDir, 'DEPLOY.md');
      if (deployMd) {
        const envs = parseDeployMd(deployMd);
        if (envs.length > 0) {
          const rows = envs.map((e) => {
            const vars = e.envVars.length > 0
              ? e.envVars.map((v) => `\`${v}\``).join(', ')
              : '—';
            return `| **${e.name}** | ${vars} |${e.notes ? ` ${truncate(e.notes, 60)} |` : ' |'}`;
          });
          sections.push(
            `## Deploy environments\n\n` +
            `| Environment | Required vars | Notes |\n` +
            `|-------------|--------------|-------|\n` +
            rows.join('\n') +
            `\n\n> Commands are in DEPLOY.md — never stored here for security.`,
          );
          this.reporter.success(`  ${envs.length} deploy environment(s) listed from DEPLOY.md`);
        }
      }
    }

    // ── Assemble ──────────────────────────────────────────────────────────────
    const bundle = sections.join('\n\n') + '\n';

    // Run SecretScanner on the final bundle as a safety net
    const scan = this.scanner.scan(bundle, OUTPUT_FILE);
    if (scan.hasSecrets) {
      this.reporter.warn('Secret pattern detected in generated bundle — aborting write.');
      for (const f of scan.findings) {
        this.reporter.warn(`  Line ${f.line}: ${f.pattern} [${f.severity}]`);
      }
      return;
    }

    const outputPath = path.join(targetDir, OUTPUT_FILE);
    const approxTokens = Math.round(bundle.length / 4);

    if (dryRun) {
      this.reporter.blank();
      this.reporter.dryRun(`Would write ${OUTPUT_FILE} (${approxTokens} tokens estimated):`);
      this.reporter.blank();
      process.stdout.write(bundle + '\n');
      return;
    }

    await fs.writeFile(outputPath, bundle, 'utf-8');
    this.reporter.blank();
    this.reporter.success(
      `${OUTPUT_FILE} written (${approxTokens} tokens estimated).`,
    );
    this.reporter.info('Add context-bundle.md to .gitignore to avoid committing it.');
  }

  private async readSafe(dir: string, filename: string): Promise<string | null> {
    try {
      const content = await fs.readFile(path.join(dir, filename), 'utf-8');
      const scan = this.scanner.scan(content, filename);
      if (scan.hasSecrets) {
        this.reporter.warn(
          `  ${filename} contains secrets — excluded from bundle for security.`,
        );
        return null;
      }
      return content;
    } catch {
      return null;
    }
  }
}
