export const template = `# AGENTS.md — {{project.name}}

> Generated by agentctx on {{meta.generatedAt}}. Edit freely — run \`agentctx update\` to refresh auto-detected sections.

## Project Overview

**Stack:** {{stack.primary.name}}{{#if stack.primary.version}} {{stack.primary.version}}{{/if}}
**Language:** {{stack.language}}
**Package Manager:** {{stack.packageManager}}

## Architecture

This is a {{stack.primary.name}} project.
{{#stack "nextjs"}}
Router: check for \`app/\` directory (App Router) or \`pages/\` (Pages Router).
{{/stack}}
{{#if stack.isMonorepo}}
**Monorepo:** Yes — look for workspace packages before assuming single-package structure.
{{/if}}

## Directory Structure

| Path | Purpose |
|------|---------|
{{#if structure.sourceDir}}| \`{{structure.sourceDir}}/\` | Source code |
{{/if}}{{#if structure.testDir}}| \`{{structure.testDir}}/\` | Tests |
{{/if}}| \`public/\` | Static assets |

## Development Commands

\`\`\`bash
{{stack.packageManager}} install    # Install dependencies
{{stack.packageManager}} run dev    # Start dev server (http://localhost:3000)
{{stack.packageManager}} run build  # Production build
{{stack.packageManager}} run start  # Start production server
{{#if conventions.testRunner}}{{stack.packageManager}} run test   # Run tests ({{conventions.testRunner}}){{/if}}
{{#if conventions.linter}}{{stack.packageManager}} run lint   # Lint ({{conventions.linter}}){{/if}}
\`\`\`

## Conventions

{{#if conventions.linter}}- **Linter:** {{conventions.linter}}{{/if}}
{{#if conventions.formatter}}- **Formatter:** {{conventions.formatter}} — format before committing{{/if}}
{{#if conventions.testRunner}}- **Tests:** {{conventions.testRunner}} — run tests before opening PRs{{/if}}

## Agent Workflow

1. **Understand first:** read \`package.json\`, \`tsconfig.json\`, and existing code patterns before writing new code
2. **Follow the router pattern** — do not mix App Router and Pages Router conventions
3. **Imports:** use path aliases defined in \`tsconfig.json\` (usually \`@/\`)
4. **Types:** this project uses TypeScript — always add types, never use \`any\`
5. **Tests:** add or update tests for every significant change
6. **Environment variables:** access only via \`process.env\` — never hardcode secrets
`;
