export const template = `# AGENTS.md — {{project.name}}

> Generated by agentctx on {{meta.generatedAt}}.

## Project Overview

**Stack:** NestJS{{#if stack.primary.version}} {{stack.primary.version}}{{/if}}
**Language:** {{stack.language}}
**Package Manager:** {{stack.packageManager}}

## Architecture

NestJS modular architecture. Each feature lives in its own module:
- \`src/<feature>/<feature>.module.ts\` — module definition
- \`src/<feature>/<feature>.controller.ts\` — HTTP layer
- \`src/<feature>/<feature>.service.ts\` — business logic
- \`src/<feature>/<feature>.entity.ts\` — TypeORM/Prisma entity (if using ORM)
- \`src/<feature>/dto/\` — Data Transfer Objects (class-validator)

## Directory Structure

| Path | Purpose |
|------|---------|
| \`src/\` | Application source |
| \`src/app.module.ts\` | Root module |
{{#if structure.testDir}}| \`{{structure.testDir}}/\` | E2E tests |
{{/if}}| \`src/**/*.spec.ts\` | Unit tests (colocated) |

## Development Commands

\`\`\`bash
{{stack.packageManager}} install
{{stack.packageManager}} run start:dev    # dev server with watch
{{stack.packageManager}} run build        # compile TypeScript
{{stack.packageManager}} run start:prod   # production
{{stack.packageManager}} run test         # unit tests (Jest)
{{stack.packageManager}} run test:e2e     # e2e tests
{{stack.packageManager}} run lint         # ESLint
\`\`\`

## Conventions

{{#if conventions.linter}}- **Linter:** {{conventions.linter}}{{/if}}
{{#if conventions.testRunner}}- **Tests:** {{conventions.testRunner}} — colocated \`.spec.ts\` files{{/if}}
- Decorate everything — NestJS is decorator-driven; missing decorators break DI
- Use DTOs + \`class-validator\` for all incoming data — never trust raw request body
- Services are injected via constructor — no manual instantiation
- Modules must import/export providers they expose to other modules

## Agent Workflow

1. Always check the module structure before adding functionality
2. Every new feature needs its own module; register it in \`AppModule\`
3. Use the NestJS CLI conventions: \`controller\`, \`service\`, \`module\`, \`dto\`
4. Guards for auth, Interceptors for logging/transform, Pipes for validation
5. Environment variables: via \`ConfigModule\` / \`@nestjs/config\` — never hardcode
`;
