export const template = `# AGENTS.md — {{project.name}}

> Generated by agentctx on {{meta.generatedAt}}.

## Project Overview

**Stack:** {{stack.primary.name}}
**Language:** PHP
**Package Manager:** Composer

## Architecture

Laravel MVC project.

## Development Commands

\`\`\`bash
composer install            # Install PHP dependencies
php artisan serve           # Start dev server (http://localhost:8000)
php artisan migrate         # Run migrations
php artisan migrate:rollback # Rollback last migration
php artisan make:model <Name> -m  # Create model + migration
php artisan make:controller <Name> --resource  # Create resource controller
php artisan test            # Run tests (Pest/PHPUnit)
\`\`\`

## Directory Structure

\`\`\`
app/
  Http/Controllers/   # Request handlers
  Models/             # Eloquent models
  Providers/          # Service providers
routes/
  web.php             # Web routes
  api.php             # API routes
database/
  migrations/         # Database migrations
  seeders/            # Database seeders
resources/views/      # Blade templates
\`\`\`

## Conventions

- Models: use Eloquent, define \`$fillable\` or \`$guarded\`
- Controllers: thin controllers, fat services
- Routes: use named routes, group by middleware
- Validation: use Form Request classes for complex validation
- Environment: use \`.env\` file, access via \`env()\` or \`config()\`

## Agent Workflow

1. Check \`routes/\` before adding new endpoints
2. Use \`php artisan make:\` commands to generate boilerplate
3. Always add migrations for schema changes
4. Run \`php artisan test\` before marking work complete
`;
