export const template = `# AGENTS.md — {{project.name}}

> Generated by agentctx on {{meta.generatedAt}}. Edit freely — run \`agentctx update\` to refresh auto-detected sections.

## Project Overview

**Stack:** Design System
**Language:** {{stack.language}}
**Package Manager:** {{stack.packageManager}}

## Architecture

This workspace is a **shared design system** consumed by other packages in the monorepo.

Key files to check:
- \`tailwind-preset.js\` / \`tailwind-preset.ts\` → Tailwind configuration preset for consuming apps
- \`tailwind-plugin.js\` / \`tailwind-plugin.ts\` → Custom Tailwind plugins (utilities, components, variants)
- \`tokens.json\` / \`tokens.ts\` → Design tokens (colors, spacing, typography)
- \`theme.js\` / \`theme.ts\` → Theme configuration

## How to consume this package

In consuming workspaces, extend Tailwind with this preset:

\`\`\`js
// tailwind.config.js (consuming workspace)
const designSystem = require('{{project.name}}');

module.exports = {
  presets: [designSystem],
  // workspace-specific overrides below
};
\`\`\`

## Development Commands

\`\`\`bash
{{stack.packageManager}} install    # install dependencies
{{stack.packageManager}} run build  # build the package
\`\`\`

## Agent Workflow

1. **Never override tokens directly** — extend or alias them via the preset
2. **Check consuming workspaces** before changing any token or class name — breaking changes propagate silently
3. **Document every exported token** with its intended use case
4. **Semantic names only** — use \`color-primary\` not \`color-blue-500\`
`;
