import fs from 'node:fs/promises';
import path from 'node:path';
import type { Feature, FeatureBehavior } from '../features/types.js';

export interface ScanResult {
  feature: Feature;
}

const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs']);

const IGNORED_DIRS = new Set(['node_modules', '.git', 'dist', 'build', '.next', 'coverage', '__pycache__', '.venv']);

// ─── Patterns ───────────────────────────────────────────────────────────────

const EXPRESS_ROUTE_RE =
  /(?:app|router)\s*\.\s*(?:get|post|put|patch|delete|all)\s*\(\s*['"`](\/[^'"`\s]*)/gi;

const NESTJS_DECORATOR_RE =
  /@(?:Get|Post|Put|Delete|Patch|All)\s*\(\s*['"`]([^'"`]*)/gi;

const COMMANDER_RE =
  /\.command\s*\(\s*['"`]([^'"`<\s]+)/gi;

// ─── ID helpers ─────────────────────────────────────────────────────────────

function routeToId(route: string): string {
  return route
    .split('/')
    .filter((seg) => seg && !seg.startsWith(':') && !seg.startsWith('{'))
    .join('-')
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '')
    || 'home';
}

function fileToPageId(filePath: string, baseDir: string): string {
  const rel = filePath
    .slice(baseDir.length)
    .replace(/\\/g, '/')
    .replace(/^\//, '');

  const withoutExt = rel.replace(/\.[^.]+$/, '');
  const parts = withoutExt
    .split('/')
    .filter((p) => p && p !== 'index' && p !== '(index)' && !p.startsWith('(') && !p.startsWith('['));

  if (parts.length === 0) return 'home';
  return parts.join('-').toLowerCase().replace(/[^a-z0-9-]/g, '');
}

function makeStubBehavior(id: string, source: string): FeatureBehavior {
  return {
    flow: [`[TODO] Document the user-facing flow for "${id}" (auto-detected from ${source})`],
    date: new Date().toISOString().split('T')[0]!,
    notes: 'Stub generated by agentctx feature scan — replace with real behavior description.',
  };
}

// ─── File walker ────────────────────────────────────────────────────────────

async function walkDir(dir: string): Promise<string[]> {
  const files: string[] = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return files;
  }
  for (const entry of entries) {
    if (IGNORED_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkDir(full)));
    } else if (entry.isFile() && SOURCE_EXTENSIONS.has(path.extname(entry.name))) {
      files.push(full);
    }
  }
  return files;
}

// ─── Scanners ───────────────────────────────────────────────────────────────

async function scanExpressRoutes(projectRoot: string): Promise<ScanResult[]> {
  const files = await walkDir(projectRoot);
  const results: ScanResult[] = [];

  for (const file of files) {
    let src: string;
    try {
      src = await fs.readFile(file, 'utf-8');
    } catch {
      continue;
    }

    const routes: string[] = [];
    let match: RegExpExecArray | null;
    EXPRESS_ROUTE_RE.lastIndex = 0;
    while ((match = EXPRESS_ROUTE_RE.exec(src)) !== null) {
      routes.push(match[1]!);
    }

    for (const route of routes) {
      const id = routeToId(route);
      if (!id) continue;
      const rel = path.relative(projectRoot, file);
      results.push({
        feature: {
          id,
          files: [rel],
          status: 'active',
          current: makeStubBehavior(id, rel),
          history: [],
        },
      });
    }
  }

  return results;
}

async function scanNestJSRoutes(projectRoot: string): Promise<ScanResult[]> {
  const files = await walkDir(projectRoot);
  const results: ScanResult[] = [];

  for (const file of files) {
    let src: string;
    try {
      src = await fs.readFile(file, 'utf-8');
    } catch {
      continue;
    }

    if (!src.includes('@nestjs/')) continue;

    NESTJS_DECORATOR_RE.lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = NESTJS_DECORATOR_RE.exec(src)) !== null) {
      const route = match[1]!;
      const id = routeToId('/' + route);
      if (!id) continue;
      const rel = path.relative(projectRoot, file);
      results.push({
        feature: {
          id,
          files: [rel],
          status: 'active',
          current: makeStubBehavior(id, rel),
          history: [],
        },
      });
    }
  }

  return results;
}

async function scanNextPages(projectRoot: string): Promise<ScanResult[]> {
  const results: ScanResult[] = [];

  for (const base of ['pages', 'app']) {
    const baseDir = path.join(projectRoot, base);
    try {
      await fs.access(baseDir);
    } catch {
      continue;
    }

    const files = await walkDir(baseDir);
    for (const file of files) {
      const name = path.basename(file);
      // Skip API routes and special Next.js files
      if (
        file.includes(path.sep + 'api' + path.sep) ||
        name.startsWith('_') ||
        name.startsWith('layout') ||
        name.startsWith('loading') ||
        name.startsWith('error') ||
        name.startsWith('not-found') ||
        name.startsWith('template') ||
        (base === 'app' && name !== 'page.tsx' && name !== 'page.ts' && name !== 'page.jsx' && name !== 'page.js')
      ) {
        continue;
      }

      const id = fileToPageId(file, baseDir);
      const rel = path.relative(projectRoot, file);
      results.push({
        feature: {
          id,
          files: [rel],
          status: 'active',
          current: makeStubBehavior(id, rel),
          history: [],
        },
      });
    }
  }

  return results;
}

async function scanCliCommands(projectRoot: string): Promise<ScanResult[]> {
  const files = await walkDir(projectRoot);
  const results: ScanResult[] = [];

  for (const file of files) {
    let src: string;
    try {
      src = await fs.readFile(file, 'utf-8');
    } catch {
      continue;
    }

    if (!src.includes('.command(') && !src.includes('.command (')) continue;

    COMMANDER_RE.lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = COMMANDER_RE.exec(src)) !== null) {
      const cmd = match[1]!.split(' ')[0]!; // take first word (e.g. "deploy <env>" → "deploy")
      if (!cmd || cmd.length > 40) continue;
      const id = cmd.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
      const rel = path.relative(projectRoot, file);
      results.push({
        feature: {
          id,
          files: [rel],
          status: 'active',
          current: makeStubBehavior(id, rel),
          history: [],
        },
      });
    }
  }

  return results;
}

// ─── Public API ──────────────────────────────────────────────────────────────

export interface ScanOptions {
  mode?: 'auto' | 'routes' | 'pages' | 'cli';
}

export async function scanFeatures(projectRoot: string, opts: ScanOptions = {}): Promise<ScanResult[]> {
  const mode = opts.mode ?? 'auto';
  const all: ScanResult[] = [];

  if (mode === 'auto' || mode === 'pages') {
    all.push(...(await scanNextPages(projectRoot)));
  }
  if (mode === 'auto' || mode === 'routes') {
    all.push(...(await scanExpressRoutes(projectRoot)));
    all.push(...(await scanNestJSRoutes(projectRoot)));
  }
  if (mode === 'auto' || mode === 'cli') {
    all.push(...(await scanCliCommands(projectRoot)));
  }

  // Deduplicate: same id + same file → keep first
  const seen = new Map<string, ScanResult>();
  for (const result of all) {
    const key = result.feature.id;
    if (!seen.has(key)) seen.set(key, result);
  }

  return [...seen.values()];
}
