export const template = `# AGENTS.md — {{project.name}}

> Monorepo — Generated by aggentctx on {{meta.generatedAt}}.

## Workspaces

{{#each stack.workspaces}}### {{this.name}} (\`{{this.path}}\`)

- **Stack:** {{this.stackName}}
- **Language:** {{this.language}}
- See [\`{{this.path}}/AGENTS.md\`]({{this.path}}/AGENTS.md) for stack-specific context

{{/each}}
## Development Setup

<!-- Add root-level setup instructions here -->

## Agent Workflow

1. Before working in any workspace, read its own \`AGENTS.md\` first
2. Root-level changes (CI, shared config, root scripts) affect all workspaces
3. Never hardcode secrets — use environment variables
4. When changing shared code, check which workspaces depend on it
`;
